[FLIN-81] Add relational database to container
FlinkFood/FlinkFood pull request #11
Opened 2023-11-08 18:01 UTC by MarcosPetrucci

## User Story
As a user, I would want my app to be containarized, So that it would be easier to maintain

## Acceptance criteria
- [ ] Has a relational database container
- [ ] Has a mock SQL

## Describe your changes
- Added a `flink-food.sql` containing a mock database plus toy data
- Added the adequate database schema under doc
- Configured the database container

## Github issue this pull requests addresses
Closes issue #9 
Closes issue #10 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have updated/created the corresponding documentation

## Observations
An automated script to insert data from the SQL file into the container was not requested. I tried it and could not do it right away, as it is _cool_ feature, not necessary at all, I am creating this PR.

2023-11-08 18:02 UTC, MarcosPetrucci commented
Request @PolimiGiovanniArriciati review specially about the database schema

2023-11-08 22:55 UTC, PolimiGiovanniArriciati requested changes

2023-11-08 22:55 UTC, PolimiGiovanniArriciati commented on docker-compose.yml
> -      test: "pg_isready -U postgresuser -d shipment_db"
The internal health check is really awesome!

2023-11-08 22:55 UTC, PolimiGiovanniArriciati commented on scripts/insert_sql.sh
We should remove this file

2023-11-08 22:55 UTC, PolimiGiovanniArriciati commented on docker-compose.yml
>      image: debezium/postgres:13
Not sure about the version, I would use `postgres:16-alpine`

2023-11-09 10:53 UTC, merged

2023-11-09 11:36 UTC, MarcosPetrucci commented on docker-compose.yml
> +    image: debezium/postgres:16-alpine
Just to let @VegSja and @febagni we changed the postgreSQL image to a newer one given some compatibility issues with Gio's Mac