[Flin 81] add relational database to container
FlinkFood/FlinkFood pull request #15
Opened 2023-11-09 16:42 UTC by PolimiGiovanniArriciati

## Describe your changes
Now the data of the db is persisted externally from the container and at each run there are me and Marcos in the `CLIENT` table!

## Github issue this pull requests addresses
Closes issue #9 

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have updated/created the corresponding documentation

2023-11-09 17:54 UTC, VegSja requested changes
There is some changes in docker compose etc. that should not be in  this pr. I think this will be resolved when merging my and felipes PR. I suspect this is because you have merged some changed from that PR into this one. But no worries. We merge me and Felipe's and then we see :)

2023-11-10 10:41 UTC, VegSja submitted a review, later dismissed

2023-11-10 15:14 UTC, MarcosPetrucci approved these changes

2023-11-10 15:22 UTC, MarcosPetrucci approved these changes

2023-11-10 15:24 UTC, MarcosPetrucci approved these changes

2023-11-10 15:26 UTC, merged