[FLIN-91] Create GitHub guide on how to commit the work done and how to reviw it
FlinkFood/FlinkFood pull request #26
Opened 2023-11-15 11:07 UTC by AZANK7173

---
name: Pull Request
title: '[FLIN-91] Create GitHub guide on how to commit the work done and how to reviw it'
---

## Describe your changes
Update to the README what to do reagrding commits and issue creation 

## Github issue this pull requests addresses
Closes issue #25 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

2023-11-15 16:47 UTC, PolimiGiovanniArriciati requested changes

2023-11-15 16:47 UTC, PolimiGiovanniArriciati commented on README.md
> +4. Create an issue on the GitHub page, following the pre defined template, make sure to add the reviewers of the work as the co-collaborators assigned on the Jira board
I'd remove the issue task

2023-11-20 10:33 UTC, AZANK7173 commented
@PolimiGiovanniArriciati Done :) removed issues 👍

2023-11-20 10:36 UTC, PolimiGiovanniArriciati requested changes

2023-11-20 10:36 UTC, PolimiGiovanniArriciati commented on README.md
> +To make sure that the commits and PRs are linked to the Jira issues. Make sure to follow these rules:
this does not belong here anymore

2023-11-20 10:36 UTC, PolimiGiovanniArriciati commented on README.md
> +2. Make changes, re-run the docker containers to test and commit (`git commit -m 'number_of_task/simple_commit_message'`, eg: `git commit -m '91/update_README.md'`). In case you have done the work al
As I said [here](https://discord.com/channels/1161389681842343997/1174250586758201355/1175111183251017799) this does not work

2023-11-20 10:36 UTC, PolimiGiovanniArriciati commented on db_entries/init.sql
?

2023-11-20 10:56 UTC, PolimiGiovanniArriciati submitted a review, later dismissed
For me now we are good, If it's okay for you merge the branch

2023-11-20 11:00 UTC, PolimiGiovanniArriciati approved these changes

2023-11-20 11:03 UTC, febagni requested changes

2023-11-20 11:03 UTC, febagni commented on db_entries/init.sql
>  INSERT INTO CLIENT (GENDER, NAME, AGE, FAVORITE_FOOD) VALUES('M', 'MARCOS PETRUCCI', 23, 'PASTA AL POMODORO');
repeated line

2023-11-20 11:03 UTC, febagni commented on db_entries/init.sql
>  INSERT INTO CLIENT (GENDER, NAME, AGE, FAVORITE_FOOD) VALUES('M', 'MARCOS PETRUCCI', 23, 'PASTA AL POMODORO');
must be removed

2023-11-20 11:06 UTC, febagni approved these changes
Looks good to me

2023-11-20 11:06 UTC, merged